version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
        SMTP_HOST: ${SMTP_HOST}
        SMTP_PORT: ${SMTP_PORT}
        SMTP_USER: ${SMTP_USER}
        SMTP_PASS: ${SMTP_PASS}
        MFA_EMAIL_FROM: ${MFA_EMAIL_FROM}
        LOGIN_LINK: ${LOGIN_LINK}
        MFA_RECOVERY_LINK: ${MFA_RECOVERY_LINK}

    env_file:
      - .env

    ports:
      - "3000:3000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/_next/static/favicon.ico"]
      interval: 30s
      timeout: 10s
      retries: 3
